### PR TITLE
Fixes #187

### LINKED ISSUE #187: Implicit conversion loses integer precision
```cpp
template <typename T>
inline Require<Integral<T> && sizeof(T) == 1, istream&> read(istream& in, T& out) {
    out = in.get();
    if (!in) {
        throw system_error(error::unexpected_eof);
    }
    return in;
}
```

> ozo/include/ozo/impl/read.h:26: warning: implicit conversion loses integer precision: 'std::basic_istream<char, std::char_traits<char> >::int_type' (aka 'int') to 'char' [-Wimplicit-int-conversion]
>     out = in.get();
>         ~ ~~~^~~~~

> ozo/include/ozo/impl/read.h:51: in instantiation of function template specialization 'ozo::impl::read<char>' requested here
>     read(in, tmp);
>     ^

My suggestion is to use `boost::numeric_cast`

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

File: include/ozo/impl/read.h [hunk 1]
```diff
@@ -23,10 +23,11 @@ inline Require<RawDataWritable<T>, istream&> read(istream& in, T& out) {
 
 template <typename T>
 inline Require<Integral<T> && sizeof(T) == 1, istream&> read(istream& in, T& out) {
-    out = in.get();
-    if (!in) {
+    istream::traits_type::int_type c = in.get();
+    if (!in && istream::traits_type::not_eof(c)) {
```
Comment (thed636) [inline include/ozo/impl/read.h]: EOF checking is not needed, `if (!in)` is enough. In other cases the functionality is broken - see the test that fails. So it looks like the best solution is:

```c++
in.get(out);
if (!in) {
    throw system_error(error::unexpected_eof);
}
return in;
```

**Review by thed636 — CHANGES_REQUESTED** [review]

File: include/ozo/impl/read.h (hunk 1 above)
Comment (jonesmz) [reply include/ozo/impl/read.h]: Now all of the tests pass.

Did you still want the check for EOF removed?

Comment (thed636) [reply include/ozo/impl/read.h]: Oops, I didn't figure out that the problem is the negation absence. Well, for now, I'd ask you to remove `EOF` checking, since it may change the throwing exception behaviour, which in case of an additional `EOF` checking depends on [std::basic_ios::exceptions()](https://en.cppreference.com/w/cpp/io/basic_ios/exceptions) method. It looks like a test case should be added to enforce such behavior.

It is clear that such behavior may hide the initial problem with the stream. For that case, the solution which throws a proper exception is needed. And IMO this is a subject for other PR.

Comment (jonesmz) [reply include/ozo/impl/read.h]: Ok. I've removed the check for `not_eof(c)`

File: include/ozo/impl/read.h [hunk 2]
```diff
@@ -23,10 +23,12 @@ inline Require<RawDataWritable<T>, istream&> read(istream& in, T& out) {
 
 template <typename T>
 inline Require<Integral<T> && sizeof(T) == 1, istream&> read(istream& in, T& out) {
-    out = in.get();
+    istream::traits_type::int_type c = in.get();
+    // TODO: Check result of istream::traits_type::not_eof(c)
```
Comment (thed636) [inline include/ozo/impl/read.h]: Thanks, but could you please remove this comment and open an appropriate issue instead. I do not believe in TODO comments unfortunately they have no chances to be performed in real life in opposite to ticket or issues, which are always on the board.

Thank you!

**Review by thed636 — CHANGES_REQUESTED** [review]

File: include/ozo/impl/read.h (hunk 2 above)
Comment (jonesmz) [reply include/ozo/impl/read.h]: I'm happy to work with you on this, but I think we're getting a little too deep into the minutia here.

You could have created the github issue that you want me to create, and merged this change as is (with or without the TODO: comment)

Instead, we've added another round trip between your team, and mine.

Note that I consider #187 a minor problem. I'm much more concerned with #181 . I'm still unable to use OZO to execute a query in my code. There are so many parts of OZO that are not easy to understand as an end user.

**Review by thed636 — APPROVED** [review]
Thanks a lot for the contribution and supporting the process! Sometimes it looks too annoying but it brings advantages in the future.
